### PR TITLE
Update harbour-foilnotes-pl.ts

### PR DESCRIPTION
**Pull request by atlochowski**

### CODE REVIEW

**Comment by monich** [comment]
The idea of the change was that not just Foil Notes and Foil Pics, but all (at least one more is coming!) Foil apps share the same key file.  I don't think your update reflects that :/

**Comment by atlochowski** [comment]
sorry for that mistake. fixed

**Comment by monich** [comment]
Hmm... The last commit deletes harbour-foilnotes-pl.ts - why?

**Comment by monich** [comment]
https://github.com/monich/harbour-foilnotes/compare/polish..master
I squashed two out of three commits, does that look right?

**Comment by atlochowski** [comment]
Thanks and sorry for mess.

**Pull request closed without merging**
